### ISSUE TITLE
3. Stimulus sometimes does not stop on the center of the screen. (branch: new_stim)

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblrig#376] opened 2022-01-13 11:16 UTC

**Comment by oliche** [comment] 2024-06-07 10:41
It is a race condition in Bonsai where the stimulus fails to be painted at the right time.

The problem is the way the code is designed: each parameter of the stimulus is sent one by one to bonsai (6 params) and they get updated one by one, only when the screen refreshes.

On top there is a state variable in Bonsai that instructs to paint the stimulus anew, I think it comes in this state before it has received the position and it paints the stimulus at the wrong place, and then exits the open loop. 

I had fixed one part of the issue by communicating the parameters in a different order, but if we move the wheel faster than this communication occurs the stimulus doesn't get in the right place.

**Comment by bimac** [comment] 2024-06-07 11:05
[0420b15](https://github.com/int-brain-lab/iblrig/pull/671/commits/0420b15da77a06d7071a429b93ef234bb9b132e7)

**Closed** 2024-06-07 11:05 UTC
Labels: todo
