### ISSUE TITLE
video window disappeared during the training (training ChoiceWorld)

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#180] opened 2019-04-05 10:28 UTC
**Describe the bug**
Around 38 minutes after starting the training session (training ChoiceWorld), the video window disappeared. There was no error in window prompt.

**Screenshots**
![image](https://user-images.githubusercontent.com/32096962/55621532-af0b2e80-5795-11e9-8d61-e2aa95929edb.png)

**Comment by nbonacchi** [comment] 2019-04-05 11:13
That's weird...
How's your disk space?

**Comment by karolinasocha** [comment] 2019-04-05 14:54
Nope, the disc is less than half full.

**Comment by nbonacchi** [comment] 2019-04-05 16:24
Thanks for reporting this but I cannot reproduce the bug so it's hard to fix. If this happens to more people and more rigs it's a good indication it's a software issue, otherwise might be that rig is not configured  properly or some hardware component is faulty... Not showing any error message and just silently disappearing does also not help with trying to figure out what's going on.
I'll close the issue

**Closed by nbonacchi** 2019-04-05 16:24 UTC
