### ISSUE TITLE
set the session number IDX parameter in the iblrig GUI automatically

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblrig#639] opened 2024-03-25 13:12 UTC
Ephys choice world has 12 pre-determined sequences of trials.
This index ranging from 0 to 11 is a task parameter and should be incremented at each subsequent sessions of the same subject.

The parameter is already present in iblrig, but we could re-use the infrastructure that searches past sessions for the same protocol to infer what was the last number used.

**Comment by bimac** [comment] 2024-05-20 13:32
closing as duplicate of #658

**Closed as completed by bimac** 2024-05-20 13:32 UTC
