### ISSUE TITLE
water calibration and the reward delivery during biasedChoiceWorld

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#205] opened 2019-06-20 10:15 UTC
I have just done water calibration and notice that animal that is on biasedChoiceWorld receives 3ul reward/per correct trial. I think at this stage the water reward is set to 1.5 ul. 

```
NTRIALS CORRECT:      76
NTRIALS ERROR:        12
WATER DELIVERED:      228.0 µl
TIME FROM START:      0:04:46.879796
TEMPERATURE:          26.780000686645508 ºC
AIR PRESSURE:         1008.3323974609375 mb
RELATIVE HUMIDITY:    44.6083984375 %
##########################################
2019-06-20 11:15:28.305 INFO     [_iblrig_tasks_biasedChoiceWorld.py:87] Starting trial: 89
2019-06-20 11:15:30.823 INFO     [trial_params.py:151]
##########################################
TRIAL NUM:            89
STIM POSITION:        35
STIM CONTRAST:        0.0625
STIM PHASE:           3.1206191906841663

BLOCK NUMBER:         1
BLOCK LENGTH:         90
TRIALS IN BLOCK:      89
STIM PROB LEFT:       0.5

RESPONSE TIME:        1.0701
TRIAL CORRECT:        True

NTRIALS CORRECT:      77
NTRIALS ERROR:        12
WATER DELIVERED:      231.0 µl
TIME FROM START:      0:04:49.808113
TEMPERATURE:          26.790000915527344 ºC
AIR PRESSURE:         1008.33447265625 mb
RELATIVE HUMIDITY:    44.578125 %
```

**Comment by karolinasocha** [comment] 2019-06-20 11:21
Also I see error in the end of the session that _iblrig_calibration doesn't exist in Alyx. I logged to cortexlab alyx for training sessions.  Are parameters from calibration taken from local computer or from alyx? How this might affect the training session?


C:\iblrig_params\IBL\experiments\_iblrig_tasks\setups\biasedChoiceWorld\sessions\201906~1\20190620-114252.csv - The process cannot access the file because it is being used by another process.

Unhandled Exception: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Bonsai.Program.Main(String[] args)
   at Bonsai64.Program.Main(String[] args)
Connected to https://alyx.cortexlab.net as Karolina_Socha
2019-06-20 12:16:02.332 INFO     [registration.py:47] creating session for C:\iblrig_data\Subjects\KS004\2019-06-20\001
2019-06-20 12:16:03.166 INFO     [registration.py:157] https://alyx.cortexlab.net/sessions/3d9f9a2c-0b8e-4402-a876-44283420f58c
2019-06-20 12:16:03.235 INFO     [registration.py:47] creating session for C:\iblrig_data\Subjects\KS010\2019-06-20\001
2019-06-20 12:16:04.520 INFO     [registration.py:157] https://alyx.cortexlab.net/sessions/b5d65ee0-608a-406a-91ef-af3d1332115f
2019-06-20 12:16:04.602 INFO     [registration.py:47] creating session for C:\iblrig_data\Subjects\_iblrig_calibration\2019-06-20\001
2019-06-20 12:16:04.668 ERROR    [registration.py:51] Subject: _iblrig_calibration doesn't exist in Alyx. ABORT.
done
```

**Comment by nbonacchi** [comment] 2019-06-20 11:33
Duplicate of #196

**Closed by nbonacchi** 2019-06-20 11:33 UTC
