### ISSUE TITLE
failed the sync test for audio signals detection

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#242] opened 2019-08-13 19:34 UTC
I still cannot pass the "sync test" for audio pulses detection (pybpod version 5.2.8) in ephys rig. It can detect screen pulses but not audio pulses. 
![image](https://user-images.githubusercontent.com/32096962/62971329-70ebde80-be09-11e9-8df7-f01a1690827a.png)
During the sync test, I can hear beeps and HarpSoundCard is connected to COM9. 
I re-installed and installed Harp Sound Card again but that did not help.

**Comment by nbonacchi** [comment] 2019-08-14 12:10
The message says that it found 0 missing tone sync pulses
Your problem seems to be with the frame2TTL none of the pulses were found.

Closing this, not a bug

**Closed** 2019-08-14 12:11 UTC
Labels: invalid
